### ISSUE TITLE
Consider adding a license file.

### ISSUE THREAD

**Issue by LouisGariepy** [yds12/tarsila#14]
The member crates are licensed under MIT according to their manifest, but it's good practice to also add a `LICENSE` file to the top-level of the repo, along with a notice in the `README` file.

Furthermore, I would recommend to license under `MIT/Apache-2.0` (instead of just `MIT`) for compatibility with the wider Rust ecosystem.

**Comment by yds12** [comment]
Hi, thanks for pointing this out. In this case, what's the recommended practice? Having a `LICENSE-MIT` and a `LICENSE-APACHE` files? I see that in other repos they also replicate the license files in all crates.

**Comment by yds12** [comment]
Closed by: https://github.com/yds12/tarsila/commit/5bddd6ae6d83e7e720bd47fa130257b1c5957c2b
