### ISSUE TITLE
Exporting to JPEG causing artifacts

### ISSUE THREAD

**Issue by quiet-bear** [yds12/tarsila#5]
### OS: Windows 11

Exporting to JPEG artifacts the image (doing what JPEG does best). However, in the case of pixel art, I don't believe the compression should be this bad. Since there's no option for setting compression level, JPEG doesn't seem viable for smaller images at the moment. It might be good to set compression to the lowest it can go and revisit whenever there's a dedicated menu for tweaking export settings.

Imports don't seem to be affected.

![Example](https://user-images.githubusercontent.com/65508804/226121369-b59702e7-663d-4310-9360-efe243ae6e9f.png) ![Example-JPEG](https://user-images.githubusercontent.com/65508804/226121365-f6b65148-b87e-464d-a714-aa6a5d4ff1f3.png)

### Steps to reproduce:
- Create an image ( doesn't matter whether it's created, imported, or opened from a project file)
- Export, making sure to save the file as JPEG

**Comment by yds12** [comment]
I can confirm the same behaviour on Linux. I think the `image` crate that we use to save images has some default compression level. The quick solution would be to set compression to the lowest, if this setting is available in `image`. A more long-term solution would be to have a window where you can set the JPEG compression level when exporting.

**Comment by quiet-bear** [comment]
The `image` crate does have a compression quality that is defaulted to 75 on a scale from worst quality (1) to best (100). I took a look at [this issue](https://github.com/image-rs/image/issues/1842) and it seems that the best way to have fine control over the encoder is to use it directly:

```rust
pub fn save_image<IMG: Bitmap>(bitmap: IMG, path: &str) {
    let bytes = bitmap.bytes();
    let width = bitmap.width() as u32;
    let height = bitmap.height() as u32;
    let color = image::ColorType::Rgba8;

    let file = std::fs::File::create(path).expect("Failed to create file from path");
    let buffer = std::io::BufWriter::new(file);
    let result = match ImageFormat::from_path(path)
        .unwrap_or(ImageFormat::Png)
        .into()
    {
        ImageOutputFormat::Png => {
            codecs::png::PngEncoder::new(buffer).write_image(bytes, width, height, color)
        }
        ImageOutputFormat::Jpeg(_) => codecs::jpeg::JpegEncoder::new_with_quality(buffer, 100)
            .write_image(bytes, width, height, color),
        _ => return, // Format not supported
    };

    result.expect("Failed to save image");
}
```

This does resolve JPEG compression by calling `new_with_quality` and bypassing the default quality. It might also be preferable in the future to have direct access to the encoders anyways.

**Comment by yds12** [comment]
Looks good to me, it's a pretty minimal change.

**Comment by quiet-bear** [comment]
I'll get another PR created in a bit here.
