### ISSUE TITLE
Enable github discussions on the repo

### ISSUE THREAD

**Issue by crumblingstatue** [yds12/tarsila#6]
In the repo settings, it's possible to enable a discussions feature to give a lightweight forum to have discussions about the project.
![image](https://user-images.githubusercontent.com/1521976/226124390-cd7a682d-c911-4d24-bc0b-b01f703d1117.png)

It would allow users to ask questions and the like without spamming the issue tracker.

**Comment by yds12** [comment]
Thank you for the suggestion, didn't know about this feature. Enabled!
